load data
INFILE 'vendors.dat'
INTO TABLE VENDORS
TRUNCATE
FIELDS TERMINATED BY ',' TRAILING NULLCOLS
(ID POSITION(1:10) CHAR "TO_NUMBER(:ID)",
 NAME POSITION(11:30) CHAR,
 BIRTH POSITION(31:38) DATE "YYYYMMDD")